name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: TrentD815
          template: classic
          base: ""
          config_timezone: America/New_York
          plugin_habits: yes
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_trim: yes
          plugin_habits_charts: yes
          
         
