name: Metrics
on:
  schedule: [{cron: "0 1 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
    - name: 💡 Habits plugin
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_habits_from: 200               # Use 200 events to compute habits
          plugin_habits_days: 30                # Keep only events from last year
          plugin_habits_trim: yes               # Trim unused hours on daily chart
          config_timezone: America/New_York     # Set timezone
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          
          
         
