name: Metrics
on:
  schedule: [{cron: "0 1 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
    - name: 💡 Habits plugin (charts)
    
      if: ${{ success() || failure() }}
    
      uses: lowlighter/metrics@latest
      with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_habits_from: 200
          plugin_habits_days: 30
          plugin_habits_trim: yes
          config_timezone: Europe/Paris
          
          
         
